# Generated by Django 3.1.4 on 2020-12-30 22:08

import datetime
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SortRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=100)),
                ('data', models.CharField(default='', max_length=10000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('elapsed_time', models.FloatField(default=-1)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
